steps:
  - name: 'golang'
    args: ['go', 'test', '-race', './...', '-v']
  - name: 'golang'
    args: ['go', 'build', '-v', 'containers/general', '-o', 'lc_adapter_linux_64']
  - name: 'golang'
    args: ['go', 'build', '-v', 'containers/general', '-o', 'lc_adapter_windows_64.exe']
    env:
      - 'GOOS=windows'
      - 'GOARCH=amd64'
  - name: 'golang'
    args: ['go', 'build', '-v', 'containers/general', '-o', 'lc_adapter_macos_64']
    env:
      - 'GOOS=darwin'
      - 'GOARCH=amd64'
  - name: 'golang'
    args: ['go', 'build', '-v', 'containers/general', '-o', 'lc_adapter_macos_arm64']
    env:
      - 'GOOS=darwin'
      - 'GOARCH=arm64'