steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=build_conf/cloudbuild-github.enc
  - --plaintext-file=/workspace/id_rsa
  - --location=global
  - --keyring=external-repos
  - --key=github
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --network
  - cloudbuild
  - -t
  - gcr.io/$PROJECT_ID/github.com/refractionpoint/usp-adapter:$TAG_NAME
  - -t
  - refractionpoint/lc-adapter:$TAG_NAME
  - .
- name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push refractionpoint/lc-adapter:$TAG_NAME']
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/DOCKERHUB/versions/latest
    env: 'PASSWORD'
  - versionName: projects/${PROJECT_ID}/secrets/DOCKERHUB_USERNAME/versions/latest
    env: 'USERNAME'
images:
  - gcr.io/$PROJECT_ID/github.com/refractionpoint/usp-adapter:$TAG_NAME